### ISSUE TITLE
GoogleMapsResults(['There are no local results matching your search!'])

### ISSUE THREAD

**Issue by fabioselau077** [jakeee51/gomaps#6]
All keywords whithout this example "Tops Diner" return There are no local results matching your search!

**Comment by jakeee51** [comment]
Greetings,

The issue was that the resulting list was persisting scraped data from previous requests as a class attribute rather than an instance attribute. Update to the current version. https://pypi.org/project/gomaps/0.3.6/ 

Also, the error is self explanatory, you might not be providing enough context to your query. Google Maps takes in to account your location, so it may not match a place that _**isn't**_ local to you.

If you're issue persists please provide more details pertaining to your issue (i.e.: logs, code snippet, query input, etc.).

**Comment by sajadGheysar** [comment]
Hi. I'm using version 0.3.6, but this issue still persists.
![image](https://github.com/jakeee51/gomaps/assets/54141473/009eae13-3451-4ce3-ae5d-eab03239333b)
